POST http://localhost:9000/auth/signup
Content-Type: application/json

{
    "firstName":"one",
    "lastName":"demo",
    "email":"one@gmail.com",
    "password":"test"    
}

###

POST http://localhost:9000/auth/login
Content-Type: application/json

{
    "email":"user@gmail.com",
    "password":"test"
}

### Refresh Token

POST http://localhost:9000/auth/token
Content-Type: application/json

{
    "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXJAZ21haWwuY29tIiwiaWF0IjoxNjc1NTE1NTAzfQ.885RDq7jGwpKmseQ-U6mupth9qPEVmTh8zbV4pifacE"
}
### For Events
GET http://localhost:9000/event/events
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NzU1MTU1ODAsImV4cCI6MTY3NTUxNTYxMH0.sb37iVW9N5Ns9bXx12DoDaD9Ux-8h2vP8EIESJDU3eU

###
POST http://localhost:9000/user/users
Content-Type: application/json

{
    "firstName": "Sat1",
    "lastName": "Dev1",
    "email": "temp1@gmail.com",
    "password": "test",
    "role": "editor",
    "isActivated": true
}