POST http://localhost:9000/auth/signup
Content-Type: application/json

{
    "firstName":"one",
    "lastName":"demo",
    "email":"one@gmail.com",
    "password":"test"    
}

###

POST http://localhost:9000/auth/login
Content-Type: application/json

{
    "email":"user@gmail.com",
    "password":"test"
}

### For Events
GET http://localhost:9000/event/events
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ0.eyJlbWFpbCI6InVzZXJAZ21haWwuY29tIiwiaWF0IjoxNjc1NTEyMzIyfQ.xsNG9pXfD4c_w-51AdDfpLj2bW4qM15hj_CZsukDN8k

###
POST http://localhost:9000/user/users
Content-Type: application/json

{
    "firstName": "Sat1",
    "lastName": "Dev1",
    "email": "temp1@gmail.com",
    "password": "test",
    "role": "editor",
    "isActivated": true
}