POST http://localhost:9000/auth/signup
Content-Type: application/json

{
    "firstName":"one",
    "lastName":"demo",
    "email":"one@gmail.com",
    "password":"test"    
}

###

POST http://localhost:9000/auth/login
Content-Type: application/json

{
    "email":"user@gmail.com",
    "password":"test"
}

### Refresh Token Generate

POST http://localhost:9000/auth/token
Content-Type: application/json

{
    "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXJAZ21haWwuY29tIiwiaWF0IjoxNjc1NTE2NDgyfQ.lwIyB2n1QvrRrtLO0JI2zgOWUvtRUhwxxv_KL-mX3pg"
}
### For Events
GET http://localhost:9000/event/events
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NzU1MTY1MTgsImV4cCI6MTY3NTUxNjU0OH0.RH15HcypVoAiegsyxewOWPILVkoNcg3dkNZgRevOOm8

### Logout Remove Refresh Token
DELETE http://localhost:9000/auth/logout
Content-Type: application/json

{
    "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXJAZ21haWwuY29tIiwiaWF0IjoxNjc1NTE2NDgyfQ.lwIyB2n1QvrRrtLO0JI2zgOWUvtRUhwxxv_KL-mX3pg"
}


###
POST http://localhost:9000/user/users
Content-Type: application/json

{
    "firstName": "Sat1",
    "lastName": "Dev1",
    "email": "temp1@gmail.com",
    "password": "test",
    "role": "editor",
    "isActivated": true
}